title: "agitROS"
remote_theme: pmarsceill/just-the-docs
email: ras@ee.ufcg.edu.br
description: >- # this means to ignore newlines until "baseurl:"
  This repository stores the translation file of the book "A Gentle Introduction to ROS" of Jason O'Kane. We will translate it to Portuguese (Brasil).
baseurl: "/agitROS" # the subpath of your site, e.g. /blog
url: "https://ras-ufcg.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  ras-ufcg

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Aux links for the upper right navigation
aux_links:
  "RAS/UFCG Website":
    - "//edu.ieee.org/br-ufcgras/ras/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
# markup / liquid-based content.
footer_content: "Copyright &copy; 2021 RAS/UFCG Student Branch and Jason O'Kane. Distributed by an <a href=\"https://github.com/ras-ufcg/agitROS/blob/main/LICENSE\">CC0 1.0 Universal license.</a>"


# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/ras-ufcg/agitROS" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

